kind: Secret
apiVersion: v1
metadata:
  name: ranger-password-secret
  labels:
    {{- include "app.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.admin.passwords.admin }}
  admin.passwords.admin: {{ .Values.admin.passwords.admin | b64enc }}
  {{- else }}
  admin.passwords.admin: {{ quote "" }}
  {{- end }}
  {{- if .Values.admin.passwords.tagsync }}
  admin.passwords.tagsync: {{ .Values.admin.passwords.tagsync | b64enc }}
  {{- else }}
  admin.passwords.tagsync: {{ quote "" }}
  {{- end }}
  {{- if .Values.admin.passwords.usersync }}
  admin.passwords.usersync: {{ .Values.admin.passwords.usersync | b64enc }}
  {{- else }}
  admin.passwords.usersync: {{ quote "" }}
  {{- end }}
  {{- if .Values.admin.passwords.keyadmin }}
  admin.passwords.keyadmin: {{ .Values.admin.passwords.keyadmin | b64enc }}
  {{- else }}
  admin.passwords.keyadmin: {{ quote "" }}
  {{- end }}
  {{- if .Values.admin.truststore.password }}
  admin.truststore.password: {{ .Values.admin.truststore.password | b64enc }}
  {{- else }}
  admin.truststore.password: {{ quote "" }}
  {{- end }}
  {{- if .Values.admin.keystore.password }}
  admin.keystore.password: {{ .Values.admin.keystore.password | b64enc }}
  {{- else }}
  admin.keystore.password: {{ quote "" }}
  {{- end }}
  {{- if .Values.usersync.tls.truststore.password }}
  usersync.tls.truststore.password: {{ .Values.usersync.tls.truststore.password | b64enc }}
  {{- else }}
  usersync.tls.truststore.password: {{ quote "" }}
  {{- end }}
