kind: Secret
apiVersion: v1
metadata:
  name: ranger-database-password
  labels:
    {{- include "app.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if eq .Values.database.type "internal" }}
  databasePassword: {{ .Values.database.internal.databasePassword | b64enc }}
  databaseRootPassword: {{ .Values.database.internal.databaseRootPassword | b64enc }}
  {{- if .Values.database.internal.databaseAdminPassword }}
  databaseAdminPassword: {{ .Values.database.internal.databaseAdminPassword | b64enc }}
  {{- end }}
  {{- end }}
  {{- if eq .Values.database.type "external" }}
  databasePassword: {{ .Values.database.external.databasePassword | b64enc }}
  databaseRootPassword: {{ .Values.database.external.databaseRootPassword | b64enc }}
  {{- end }}
