{{- if .Values.initFile }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.init-file-secret.name" . }}
stringData:
{{- $globdata := .Files.Glob .Values.initFile }}
{{- if $globdata }}
{{ (tpl ($globdata).AsConfig $ ) | indent 2 }}
  initFile: |
    #!/usr/bin/env bash
    {{ range $path, $_ :=  $globdata }}
      bash /init/{{ base $path }} "$@"
    {{ end }}
{{- else }}
{{ (tpl (.Files.Glob "files/initFile.sh").AsConfig $ ) | indent 2 }}
  initFile: | {{ .Values.initFile | nindent 4 }}
{{- end }}
{{- end }}
